var queued=0,logging=!1,checked=0,invalid=0,warning=0,redirected=0,passed=0,tabId=null,moveLock=!1,processStart=Date.now();const targetClassName="ext_Link",classesToRemove="ext_Redirect ext_Valid ext_Invalid ext_Response ext_Link ext_excluded".split(" ");window.__myContentScriptInjected=!0;
var isCanvasEditor=!1,css="\n.ext_Link {\n   /* background: #333 !important;\n    color: #fff !important;\n    font-weight: bold;\n    border-right: 1px solid #fff;*/\n}\n\n.ext_Invalid {\n    background: #990000 !important;\n    color: #fff !important;\n}\n\n.ext_Valid {\n    background: #669900 !important;\n    color: #fff !important;\n}\n\n.ext_Redirect {\n    color: #fff !important;\n}\n\n.ext_Warning {\n    background: #D5DE23 !important;\n    color: #fff !important;\n}\n\n.ext_Response {\n    color: #fff;\n    border-left: 1px solid #fff;\n    padding: 0px 5px;\n    margin: 0px 0px 0px 5px;\n}",running=
!0;
function addIframe(a){document.getElementById("checkmylinkdiv")||chrome.storage.local.get(["redirectColor","validColor","warningColor","invalidColor","cPosition"],b=>{var f=document.createElement("div");f.id="checkmylinkdiv";var c=document.createElement("iframe");c.src=chrome.runtime.getURL("tools/link-checker/pages/linkreport.html?tabid="+a);c.style.width="100%";c.style.height="100%";c.style.borderRadius="12px";c.style.border="none";c.id="check-my-link-iframe";f.appendChild(c);document.body.appendChild(f);"undefined"==typeof b.cPosition?
(chrome.storage.local.set({cPosition:"left"}),$("#checkmylinkdiv").css("position","revert-layer"),$("#checkmylinkdiv").css({top:50,right:50,left:"auto"})):($("#checkmylinkdiv").css("position","revert-layer"),"right"===b.cPosition?$("#checkmylinkdiv").css({top:50,left:50,right:"auto"}):$("#checkmylinkdiv").css({top:50,right:50,left:"auto"}));c=`.ext_Valid {
        background: ${b.validColor} !important;
        }`;var e=`.ext_Invalid {
        background: ${b.invalidColor} !important;  
    }`;f=`.ext_Warning {
        background: ${b.warningColor} !important;
    }`;b=`.ext_Redirect {
        background: ${b.redirectColor} !important;
    }`;var d=document.createElement("style");d.type="text/css";d.id="ext-all-css";d.styleSheet?d.styleSheet.cssText=css:d.appendChild(document.createTextNode(css));document.head.appendChild(d);d=document.createElement("style");d.id="ext-invalidColor";d.type="text/css";d.styleSheet?d.styleSheet.cssText=e:d.appendChild(document.createTextNode(e));document.head.appendChild(d);e=document.createElement("style");e.id="ext-validColor";e.type="text/css";e.styleSheet?e.styleSheet.cssText=c:e.appendChild(document.createTextNode(c));
document.head.appendChild(e);c=document.createElement("style");c.id="ext-redirectColor";c.type="text/css";c.styleSheet?c.styleSheet.cssText=b:c.appendChild(document.createTextNode(b));document.head.appendChild(c);c=document.createElement("style");c.id="ext-warningColor";c.type="text/css";c.styleSheet?c.styleSheet.cssText=f:c.appendChild(document.createTextNode(f));document.head.appendChild(c)})}var totalPageLinks=0;
chrome.runtime.onMessage.addListener(async(a,b,f)=>{if("changePos"==a.action)$("#checkmylinkdiv").css("position","revert-layer"),"right"===a.cPosition?$("#checkmylinkdiv").css({top:50,left:50,right:"auto"}):$("#checkmylinkdiv").css({top:50,right:50,left:"auto"});else if("startMove"==a.action)moveLock=moveLock?!1:!0;else if("stopMove"==a.action)moveLock=!1;else if("removeAllDom"==a.action)moveLock=running=!1,removeAllDom();else if("highlight-element"===a.action)window.location.hostname===a.domain&&
(addHighlightStyle(),document.querySelectorAll(".ext-highlighted-element").forEach(d=>d.classList.remove("ext-highlighted-element")),b=getElementByXPath(a.xpath))&&(b.classList.add("ext-highlighted-element"),b.scrollIntoView({behavior:"smooth",block:"center"}));else if("remove-highlight"===a.action)document.getElementById("ext-highlight-style")?.remove(),document.querySelectorAll(".ext-highlighted-element").forEach(d=>d.classList.remove("ext-highlighted-element"));else if("start"===a.action){processStart=
Date.now();if(document.getElementById("checkmylinkdiv")&&"undefined"==typeof a.actions)return running=!1,removeAllDom(),!0;"undefined"!=typeof a.actions?removeAllDom(!1):removeAllDom();({allow:b}=await chrome.storage.local.get("allow"));b?await loadExcludedElements():$(".ext_excluded").removeClass("ext_excluded");chrome.runtime.sendMessage({action:"reset",tabId});running=!0;passed=redirected=warning=invalid=0;tabId=a.tabid;window.self==window.top&&addIframe(tabId);let d=[];d=a.options.blacklist;d=
d.split("\n");let k=a.options.noFollow;var c=[];/https:\/\/docs\.google\.com\/document\//.test(window.location.href)||/https:\/\/docs\.google\.com\/spreadsheets\//.test(window.location.href)?(console.log("Google Docs/Sheets detected, using specialized link extraction."),c=(await parseLinks()).map(({url:g,text:h})=>{let l=h;if(""===h.trim()||g===h)try{l=(new URL(g)).hostname.replace(/^www\./,"")}catch(m){l=h}return Object.assign(document.createElement("a"),{href:g,textContent:l,className:"docs-link"})}),
isCanvasEditor=!0):(c=getAllShadowDomLinks(a.options.emptyLinkExclude),isCanvasEditor=!1);var e=totalPageLinks=c.length;chrome.storage.local.get(["batchProcessingEnabled","batchProcessing"],g=>{if("undefined"!=typeof g.batchProcessingEnabled&&0==g.batchProcessingEnabled){for(g=0;g<c.length;g++){var h=c[g];!0===isLinkValid(h,d,k)?(queued+=1,h.classList.add("ext_Link"),checkURL(h,a.options)):(--e,--totalPageLinks)}return!0}"undefined"==typeof g.batchProcessingEnabled&&(h={minStart:10,maxEnd:20,minDelay:2,
maxDelay:4},g.batchProcessing=h,chrome.storage.local.set({batchProcessingEnabled:!0,batchProcessing:h}));var l=g.batchProcessing;g=l.minStart;h=l.maxEnd;const m=l.minDelay;l=l.maxDelay;let n=[];for(let p=0;p<c.length;p++){let q=c[p];isLinkValid(q,d,k)?(n.push(q),q.classList.add("ext_Link")):(e--,totalPageLinks--)}queued=n.length;processBatches(n,g,h,m,l,a.options)})}else"HIDE_CHECK_MY_LINK"===a.action?(chrome.runtime.sendMessage({action:"hided"}),$("#checkmylinkdiv").hide()):"SHOW_CHECK_MY_LINK"===
a.action&&$("#checkmylinkdiv").show()});function getElementByXPath(a){return document.evaluate(a,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}
function addHighlightStyle(){if(!document.getElementById("ext-highlight-style")){var a=document.createElement("style");a.id="ext-highlight-style";a.textContent="\n        .ext-highlighted-element {\n            outline: 3px solid blue !important;\n            outline-offset: 2px !important;\n        }\n    ";document.head.appendChild(a)}}
function processBatches(a,b,f,c,e,d){function k(h){h="number"===typeof h?h:getRandom(b,f);h=Math.min(g+h,a.length);for(var l=g;l<h;l++)checkURL(a[l],d);g=h;h=a.length-g;l=1E3*getRandom(c,e);if(0<h){const m=Math.min(getRandom(b,f),h);chrome.runtime.sendMessage({action:"nextCounters",nextDelay:l/1E3,nextBatchSize:m,tabId});setTimeout(()=>{k(m)},l)}}let g=0;k()}function getRandom(a,b){a=Math.ceil(a);b=Math.floor(b);return Math.floor(Math.random()*(b-a+1))+a}
function getLinksInShadowRoot(a){const b=document.createElement("style");b.textContent=css;a.appendChild(b);return a.querySelectorAll("a")}function getLinksInIframe(a){return a.querySelectorAll("a")}
function getAllShadowDomLinks(a){a="true"==a?!0:!1;const b=[];document.querySelectorAll("*").forEach(e=>{e.shadowRoot&&b.push(e.shadowRoot)});const f=[];b.forEach(e=>{getLinksInShadowRoot(e).forEach(d=>{isExcluded(d)||(a?f.push(d):d.getAttribute("href")&&f.push(d))})});let c=document.getElementsByTagName("a");c=Array.from(c);c.forEach(e=>{isExcluded(e)||(a?f.push(e):e.getAttribute("href")&&f.push(e))});return f}function isExcluded(a){return null!==a.closest(".ext_excluded")}
function checkURL(a,b){var f=create("a",{href:a.href});chrome.runtime.sendMessage({action:"check",url:f.href},function(c){var e=[];e=getTrailingHashWarning(b,a,e);e=getParseDOMWarning(b,a.href,c,e);e=getEmptyLinkWarning(b,a.outerHTML,e);e=getNoHrefLinkWarning(b,a,e);running&&updateDisplay(a,e,c.status,b,a.href)})}
function updateDisplay(a,b,f,c,e){chrome.storage.local.get(["vt","it","rt","wt"],d=>{if(!isNaN(f)&&200<=f&&300>f&&0===b.length){a.classList.add(d.vt?"ext_Valid":"ext_Valid_t");passed+=1;d="valid";var k=[e,f,a.textContent.trim().substring(0,20)]}else if(!isNaN(f)&&300<=f&&400>f&&0===b.length)a.classList.add(d.rt?"ext_Redirect":"ext_Redirect_t"),a.classList.add(d.rt?"ext_Valid":"ext_Valid_t"),redirected+=1,d="redirect",k=[e,f,a.textContent.trim().substring(0,20),b.join(", ")];else if(!isNaN(f)&&200<=
f&&400>f&&0<b.length){for(k=0;k<b.length;k++);a.classList.add(d.wt?"ext_Warning":"ext_Warning_t");isCanvasEditor||(a.innerHTML+=' <span class="ext_Response">'+f+"</span>");warning+=1;d="warning";k=[e,f,a.textContent.trim().substring(0,20),b.join(", ")]}else console.log("Response "+f+": "+a.href),a.classList.add(d.it?"ext_Invalid":"ext_Invalid_t"),isCanvasEditor||(a.innerHTML+=' <span class="ext_Response">'+f+"</span>"),invalid+=1,d="invalid",k=[e,f,a.textContent.trim().substring(0,20)];--queued;checked+=
1;chrome.runtime.sendMessage({action:"updatedlogs",link:a,queued,invalid,warning,redirected,passed,totalPageLinks,tabId,cache:c.cache,method:c.checkType,type:d,urlObj:k,startTime:processStart})})}
chrome.storage.onChanged.addListener((a,b)=>{"undefined"!=typeof a.vt&&(1==a.vt.newValue?$(".ext_Link.ext_Valid_t").addClass("ext_Valid").removeClass("ext_Valid_t"):$(".ext_Link.ext_Valid").addClass("ext_Valid_t").removeClass("ext_Valid"));"undefined"!=typeof a.it&&(1==a.it.newValue?$(".ext_Link.ext_Invalid_t").addClass("ext_Invalid").removeClass("ext_Invalid_t"):$(".ext_Link.ext_Invalid").addClass("ext_Invalid_t").removeClass("ext_Invalid"));"undefined"!=typeof a.rt&&(1==a.rt.newValue?$(".ext_Link.ext_Redirect_t").addClass("ext_Redirect").removeClass("ext_Redirect_t ext_Valid"):
$(".ext_Link.ext_Redirect").addClass("ext_Redirect_t").removeClass("ext_Redirect ext_Valid"));"undefined"!=typeof a.wt&&(1==a.rt.newValue?$(".ext_Link.ext_Warning_t").addClass("ext_Warning").removeClass("ext_Warning_t"):$(".ext_Link.ext_Warning").addClass("ext_Warning_t").removeClass("ext_Warning"));"undefined"!=typeof a.validColor&&(document.getElementById("ext-validColor").innerHTML=`.ext_Valid {
              background: ${a.validColor.newValue} !important;
          }`);"undefined"!=typeof a.warningColor&&(b=document.getElementById("ext-warningColor"),b.innerHTML=`.ext_Warning {
            background: ${a.warningColor.newValue} !important;
        }`);"undefined"!=typeof a.redirectColor&&(b=document.getElementById("ext-redirectColor"),b.innerHTML=`.ext_Redirect {
                background: ${a.redirectColor.newValue} !important;
            }`);"undefined"!=typeof a.invalidColor&&(document.getElementById("ext-invalidColor").innerHTML=`.ext_Invalid {
            background: ${a.invalidColor.newValue} !important;
        }`)});function removeAllDom(a=!0){a&&$("#checkmylinkdiv").remove();$("#ext-all-css, #ext-invalidColor, #ext-invalidColor, #ext-redirectColor, #ext-warningColor, .ext_Response").remove();a=document.getElementsByClassName(targetClassName);Array.from(a).forEach(b=>{classesToRemove.forEach(f=>{b.classList.remove(f)})});document.querySelectorAll("*").forEach(b=>{b.shadowRoot&&processShadowDOM(b.shadowRoot)})}
function processShadowDOM(a){a&&(a.querySelectorAll(`.${targetClassName}`).forEach(b=>{removeClasses(b,classesToRemove)}),a.querySelectorAll("*").forEach(b=>{b.shadowRoot&&processShadowDOM(b.shadowRoot)}))}function removeClasses(a,b){b.forEach(f=>{a.classList.remove(f)})}document.addEventListener("mousemove",function(a){moveLock&&($("#checkmylinkdiv").css("position","revert-layer"),a={top:a.pageY-25,left:a.pageX-25},$("#checkmylinkdiv").offset(a))},!0);
window.addEventListener("message",a=>{"iframeHeight"===a.data.type&&(a=parseInt(a.data.height)+7,document.getElementById("checkmylinkdiv").style.height=a+"px")});function getDocId(){const a=location.pathname.match(/\/d\/([a-zA-Z0-9_-]+)/);return a?a[1]:null}function getDocType(){const a=location.href;return a.includes("docs.google.com/document")?"doc":a.includes("docs.google.com/spreadsheets")?"sheet":null}
function decodeHTMLEntities(a){return a.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'").replace(/&#x2F;/g,"/").replace(/&#(\d+);/g,(b,f)=>String.fromCharCode(f))}function stripTags(a){return a.replace(/<[^>]*>/g,"").trim()}function unwrapGoogleRedirect(a){if(!a)return a;try{if(a.includes("google.com/url")){const b=new URL(a);return b.searchParams.get("q")||b.searchParams.get("url")||a}}catch(b){}return a}
function isGoogleInternal(a){return a?"accounts.google.com support.google.com policies.google.com fonts.googleapis.com fonts.gstatic.com themes.googleusercontent.com ssl.gstatic.com www.gstatic.com apis.google.com play.google.com/log clients6.google.com workspace.google.com docs.google.com/static docs.google.com/css docs.google.com/js".split(" ").some(b=>a.includes(b)):!0}
function extractLinksFromHTML(a){const b=[],f=new Set,c=/<a\s[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;for(var e;null!==(e=c.exec(a));){let d=decodeHTMLEntities(e[1]);e=stripTags(decodeHTMLEntities(e[2]));!(d=unwrapGoogleRedirect(d))||d.startsWith("#")||d.startsWith("javascript:")||isGoogleInternal(d)||f.has(d)||(f.add(d),b.push({url:d,text:e||d}))}return b}
function extractUrlsFromText(a){const b=[],f=new Set;(a.match(/https?:\/\/[^\s,"'<>\\)\]]+/g)||[]).forEach(c=>{c=c.replace(/[.,;:!?)}\]]+$/,"");c=unwrapGoogleRedirect(c);isGoogleInternal(c)||f.has(c)||(f.add(c),b.push({url:c,text:""}))});return b}async function tryFetch(a,b){for(const f of a)try{const c=await fetch(f,{credentials:"include",redirect:"follow"});if(c.ok){const e=await c.text();if(e&&50<e.length)return e}}catch(c){}return null}
async function fetchDocLinks(a){a=await tryFetch([`https://docs.google.com/document/d/${a}/export?format=html`,`https://docs.google.com/document/d/${a}/mobilebasic`],"Doc HTML");if(!a)throw Error("Could not export document. Check you have access.");return extractLinksFromHTML(a)}
async function fetchSheetLinks(a){function b(g){c.has(g.url)||(c.add(g.url),f.push(g))}const f=[],c=new Set,e=new Set(["0"]);try{var d=document.documentElement.outerHTML;let g;for(var k=/"gid"\s*:\s*"?(\d+)"?/g;null!==(g=k.exec(d));)e.add(g[1]);for(k=/gid=(\d+)/g;null!==(g=k.exec(d));)e.add(g[1]);document.querySelectorAll("[data-id]").forEach(h=>{(h=h.getAttribute("data-id"))&&/^\d+$/.test(h)&&e.add(h)})}catch(g){}(d=await tryFetch([`https://docs.google.com/spreadsheets/d/${a}/htmlview`,`https://docs.google.com/spreadsheets/d/${a}/preview`,
`https://docs.google.com/spreadsheets/d/${a}/pubhtml`],"Sheet HTML"))&&extractLinksFromHTML(d).forEach(g=>b({...g,via:"hyperlink"}));for(const g of e)if(d=await tryFetch([`https://docs.google.com/spreadsheets/d/${a}/gviz/tq?tqx=out:csv&gid=${g}`,`https://docs.google.com/spreadsheets/d/${a}/export?format=csv&gid=${g}`],`CSV gid=${g}`))d=extractUrlsFromText(d),d.forEach(h=>b({...h,via:1<e.size?`cell-text (gid:${g})`:"cell-text"})),console.log(`   Found ${d.length} URL(s) from CSV gid=${g}`);if(0===
f.length)for(const g of e)(d=await tryFetch([`https://docs.google.com/spreadsheets/d/${a}/gviz/tq?tqx=out:tsv-excel&gid=${g}`],`TSV gid=${g}`))&&extractUrlsFromText(d).forEach(h=>b({...h,via:"tsv-fallback"}));return f}async function parseLinks(a={}){const b=getDocType(),f=getDocId();if(!b||!f)return[];let c;try{c="doc"===b?await fetchDocLinks(f):await fetchSheetLinks(f)}catch(e){return[]}a.includeInternal||(c=c.filter(e=>!e.url.includes(`/d/${f}`)&&!e.url.startsWith("#")));return c};
