var indexedDBHelper=function(){var a=null,e=0;return{init:function(){indexedDBHelper.open()},open:function(){return new Promise(function(c,g){var h=indexedDB.open("CheckLinks",1);h.onupgradeneeded=function(f){a=f.target.result;f.target.transaction.onerror=indexedDB.onerror;a.objectStoreNames.contains("links")&&a.deleteObjectStore("links");a.createObjectStore("links",{keyPath:"id"}).createIndex("by_link","link")};h.onsuccess=function(f){a=f.target.result;c()};h.onerror=function(f){g("Couldn't open DB")}})},
addLink:function(c,g){var h=a.transaction(["links"],"readwrite").objectStore("links");e++;return new Promise(function(f,b){var d=h.put({id:e,link:c,timeStamp:(new Date).getTime(),status:g});d.onsuccess=function(k){f()};d.onerror=function(k){console.log(k.value);b("Couldn't add the passed item")}})},getLink:function(c){var g=a.transaction(["links"],"readonly").objectStore("links");return new Promise(function(h,f){var b=g.index("by_link").get(c);b.onsuccess=function(d){h(d.target.result)};b.onerror=
function(d){f("Couldn't fetch items from the DB")}})},getAllLinks:function(){var c=[],g=a.transaction(["links"],"readonly").objectStore("links");return new Promise(function(h,f){var b=IDBKeyRange.lowerBound(0);b=g.openCursor(b);b.onsuccess=function(d){d=d.target.result;null===d||void 0===d?h(c):(c.push(d.value),d.value.id>e&&(e=d.value.id),d.continue())};b.onerror=function(d){f("Couldn't fetch items from the DB")}})},deleteLink:function(c){return new Promise(function(g,h){var f=a.transaction(["links"],
"readwrite").objectStore("links").delete(c);f.onsuccess=function(b){g()};f.onerror=function(b){console.log(b);h("Couldn't delete the item")}})},deleteObjectStore:function(c){indexedDBHelper.open().then(function(){return new Promise(function(g,h){var f=a.transaction(["links"],"readwrite").objectStore("links").clear();f.onsuccess=function(b){g()};f.onerror=function(b){console.log(b);h("Couldn't delete the item")}})},function(g){console.log(g)})}}}();indexedDBHelper.init();
function getOption(a){var e={blacklist:"doubleclick.net\nchromewebstore.google.com\nchrome.google.com\nappliedsemantics.com",checkType:"GET",cache:"false",noFollow:"false",parseDOM:"false",trailingHash:"false",emptyLink:"false",emptyLinkExclude:"false",noHrefAttr:"false",autoCheck:"false",optionsURL:"chrome-extension://"+chrome.runtime.id+"/pages/settings.html"};var c=getItem(a);(null===c||"null"==c)&&a in e&&(setItem(a,e[a]),c=e[a]);return c}
function getItem(a){console.log("Get Item:"+a);try{var e=window.localStorage.getItem(a);if("undefined"===typeof e)return null}catch(c){e=null}console.log("Returning value: "+e);return e}
function getOptions(){var a={};a.blacklist=getOption("blacklist");a.checkType=getOption("checkType");a.cache=getOption("cache");a.noFollow=getOption("noFollow");a.parseDOM=getOption("parseDOM");a.trailingHash=getOption("trailingHash");a.emptyLink=getOption("emptyLink");a.noHrefAttr=getOption("noHrefAttr");a.autoCheck=getOption("autoCheck");a.optionsURL=getOption("optionsURL");return a}
function setItem(a,e){try{console.log("Inside setItem:"+a+":"+e),window.localStorage.removeItem(a),window.localStorage.setItem(a,e)}catch(c){console.log("Error inside setItem"),console.log(c)}console.log("Return from setItem"+a+":"+e)}
function loadOptions(){chrome.storage.local.get("defaultOptions",function(a){a=a.defaultOptions;"true"==a.cache&&(document.getElementById("cache").checked=!0);"true"==a.noFollow&&(document.getElementById("noFollow").checked=!0);"true"==a.parseDOM&&(document.getElementById("parseDOM").checked=!0);"true"==a.trailingHash&&(document.getElementById("trailingHash").checked=!0);"true"==a.emptyLink&&(document.getElementById("emptyLink").checked=!0);console.log(a.emptyLinkExclude);"true"==a.emptyLinkExclude&&
(document.getElementById("emptyLinkExclude").checked=!0);"true"==a.noHrefAttr&&(document.getElementById("noHrefAttr").checked=!0);"true"==a.autoCheck&&(document.getElementById("autoCheck").checked=!0);document.getElementById("blacklistEntries").value=a.blacklist.split(" ");for(var e=document.getElementById("requestType"),c=0;c<e.children.length;c++){var g=e.children[c];if(g.value==a.checkType){g.selected="true";break}}})}
function saveOptions(){var a=document.getElementById("blacklistEntries"),e=document.getElementById("requestType");a={blacklist:a.value,checkType:e.children[e.selectedIndex].value,cache:"false",noFollow:"false",parseDOM:"false",trailingHash:"false",emptyLink:"false",emptyLinkExclude:"false",noHrefAttr:"false",autoCheck:"false",optionsURL:"chrome-extension://"+chrome.runtime.id+"/options.html"};document.getElementById("cache").checked&&(a.cache="true");document.getElementById("noFollow").checked&&(a.noFollow=
"true");document.getElementById("parseDOM").checked&&(a.parseDOM="true");document.getElementById("trailingHash").checked&&(a.trailingHash="true");document.getElementById("emptyLink").checked&&(a.emptyLink="true");document.getElementById("emptyLinkExclude").checked&&(a.emptyLinkExclude="true");document.getElementById("noHrefAttr").checked&&(a.noHrefAttr="true");document.getElementById("autoCheck").checked&&(a.autoCheck="true");document.getElementById("msg").style.display="block";document.getElementById("msgtop").style.display=
"block";chrome.storage.local.set({defaultOptions:a});setTimeout(function(){document.getElementById("msg").style.display="none";document.getElementById("msgtop").style.display="none"},2E3)}function deleteObjectStore(){indexedDBHelper.deleteObjectStore();document.getElementById("msgCache").style.visibility="visible";setTimeout(function(){document.getElementById("msgCache").style.visibility="hidden"},2E3)}document.getElementById("save").addEventListener("click",saveOptions);
document.getElementById("savetop").addEventListener("click",saveOptions);document.getElementById("clearCache").addEventListener("click",deleteObjectStore);loadOptions();
document.addEventListener("DOMContentLoaded",()=>{function a(b){h.forEach(d=>{document.getElementById(d).disabled=!b})}function e(){if(f.checked){var b=parseInt(document.getElementById("minStart").value)||0,d=parseInt(document.getElementById("maxEnd").value)||0,k=parseInt(document.getElementById("minDelay").value)||0,m=parseInt(document.getElementById("maxDelay").value)||0;g();var l=!1;b>=d&&(c("minStart","Min must be less than Max"),c("maxEnd","Max must be greater than Min"),l=!0);k>=m&&(c("minDelay",
"Min must be less than Max"),c("maxDelay","Max must be greater than Min"),l=!0);l||chrome.storage.local.set({batchProcessing:{minStart:b,maxEnd:d,minDelay:k,maxDelay:m}})}}function c(b,d){document.getElementById(b).style.border="1px solid red";document.getElementById("error-"+b).innerText=d}function g(){document.querySelectorAll(".error-box").forEach(b=>b.innerText="");h.forEach(b=>document.getElementById(b).style.border="")}if(window.location.href.includes("highlight")){const b=document.querySelector(".batch-group");
b.classList.add("active");document.querySelector("#minStart").focus();b.scrollIntoView({behavior:"smooth",block:"start"})}const h=["minStart","maxEnd","minDelay","maxDelay"],f=document.getElementById("batchToggle");chrome.storage.local.get(["batchProcessingEnabled","batchProcessing"],b=>{void 0!==b.batchProcessingEnabled&&(f.checked=b.batchProcessingEnabled);a(f.checked);b.batchProcessing&&h.forEach(d=>{void 0!==b.batchProcessing[d]&&(document.getElementById(d).value=b.batchProcessing[d])})});f.addEventListener("change",
()=>{const b=f.checked;a(b);chrome.storage.local.set({batchProcessingEnabled:b})});h.forEach(b=>{document.getElementById(b).addEventListener("change",e)})});
